# Generated by Django 2.2.5 on 2020-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dival_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(max_length=256),
        ),
    ]
