# Generated by Django 2.2.5 on 2020-01-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dival_app', '0002_auto_20200120_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='DOB',
        ),
    ]
